{% set name = "argparse-addons" %}
{% set version = "0.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/argparse_addons-{{ version }}.tar.gz
  sha256: 6322a0dcd706887e76308d23136d5b86da0eab75a282dc6496701d1210b460af

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - argparse_addons
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/eerimoq/argparse_addons
  summary: Additional argparse types and actions.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nisharai1
